# Generated by Django 4.2.2 on 2023-07-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='tema',
        ),
        migrations.AddField(
            model_name='tema',
            name='tema',
            field=models.ManyToManyField(to='api.item'),
        ),
    ]
